name: Jacoco code coverage

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v4.0.2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Jacoco code coverage
      run: mvn -B verify --file romanNumber/pom.xml
